---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Upgrade packages
  apt:
    upgrade: dist
  become: yes
  register: upgrade_result

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Set reboot flag
  set_fact:
    system_reboot_needed: "{{ reboot_required.stat.exists }}"
